{{- if eq .Values.storage.provider "generic" -}}
{{- $name := .Release.Name -}}
{{- $namespace := .Release.Namespace -}}

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels:
    "app.kubernetes.io/name": {{ $name }}
spec:
  secretName: {{ $name }}-tls-secret
  duration: {{ required "cert duration required" .Values.storage.generic.tls.certManager.duration }}
  renewBefore: {{ required "cert renewBefore required" .Values.storage.generic.tls.certManager.renewBefore }}
  privateKey:
    algorithm: ECDSA
    size: 256
  usages:
    - server auth
    - client auth
  dnsNames:
    - {{ $name }}
    - {{ $name }}.{{ $namespace }}
    - {{ $name }}.{{ $namespace }}.svc
    - {{ $name }}.{{ $namespace }}.svc.cluster.local
  issuerRef:
    name: {{ .Values.storage.generic.tls.issuerName }}
    kind: ClusterIssuer
{{- end }}
