// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xYb2/buA/+KoR+P6Ab4CTOn+227FXXa4di7VC02XC4pRgUm0602pIryWm9It/9QMl2",
	"ksb9s8Nu75ZaEh+SDx+Su2ORynIlUVrDxncs55pnaFG7X8fJKbfR4nDC52f0gf4Wo4m0yK1Qko3Z4W2O",
	"kcUY6AwkSoNdICQiRXhxXSiL8UvgBnLUcH508MdgOOjCOdpCSzo4le6kkmkJIgFhjX8nI6to3FtKIpgc",
	"I5EIjEHQPWFggTxG/W4qlV2gvhEGA9D+XQ6j/gDONEZKxoJwwhEXKcaAWis9lSxgeMuzPEU2ZlMWj/ib",
	"breLg+T1lLGACfLLv88CJnlGx46TjgsFC5jG60JojNnY6gIDZqIFZpxCY8uczhqrhZyz1SpgH7F8IHCf",
	"pbguEK6wBBGjtCIphZyvo2cV+aMFLrHGlHO7WCO6wvJRMJmQJyjndsHG/aAF2pnGRNw+gO5EGOtwGLhZ",
	"KONxznAupIEbYRc+CUueFrgVzVyr7xjZTn8w7OFcozE1+OsCdblGnzvr7LHorcg7kytp0JHxPY/P8bpA",
	"Y+lXpKRF6f7J8zwVESfove+G8N9tPPt/jQkbs//11kTv+a+md0iEOK+MeJPbcXjPY9De6DsQcslTEQPX",
	"8yJzBbMK2LG0qCVPL1AvUbsHfx+8zxLr+hMVDjAOiOc6Afyk7JEqZPz7UFVZwtgzOVZoQCoLeCuMZZ56",
	"TW360vx94LZ0IfHG6VT1AL2//QaJolY5ais8DzM0hs9xt2j+rH8t0Ycf6qObJXJcsahRWti7wtLssbYi",
	"XZf318buZXNQzajYKKJHIsVTtDzmlu8iRsvnLdL9XMV+Qi/voQ6cMj2kd2SHJKBHYgYqaYw/ISM98qwb",
	"mWWbwZQb+y1TsWsRu6YnIkNjeZbDzQLl2t0bboCuQn2Vusv50cFwOHy7BWcQDl53wkGn/2bSfz0OR+Mw",
	"/JsFLFE645aNWcwtdqzIsA2cET9auHIhfuCm+2R6Vlo0m4aHg1EYBqTkIisyNg6b56na56h3OOKbgjN5",
	"PyyBp0Ebe0jtiUHmYdITxm+RKnx9bvvyqchmqMkb3zGEj3FK1f44+sC9ax7oP82DGk2RWmqPiVaZe7wS",
	"ZeouFjPzlCxs1ceqAcK15iX9rtrRDo4v1OHqPO35U3u+dCHXailijOuG2ICiqSQTlgTQEc5fA+FVsL7m",
	"5pDHK94HZzdjxCqMCi1seUEOVrpkU7PRR7PCFjydnFx4FRQyUbv+7YNLD09h/+zYiQGHOUrUIvK0NFZp",
	"PkfXVUSEQQWfcuFyxGUMH9BOJZHFCbYBRf2HS+B6JqzmumxemfHoCmXchckCncUYjZhLCk2mrFhyS3GZ",
	"lS6aF0M6EsCssBBxGklpKKrjLDS6Hlwn59DJRI2zO5VTuV/YBU1WvpGM4dRFBCYnF/Aim5xcvCQcwtTP",
	"GZipKpFRKlB653w7nUqrKI+G/uz1+6/uq/AtRFQiCZlAA+QLxjArgYPVhWuBB/td+EIXHAhQyVRu3eGa",
	"OqRE4NaZtppLkyttIeUlahcqjYnSGLjvG61xKt0RuBFpChIp6hojpPbDJRSSr/3HZowJAFORCcltPW5K",
	"pKBT7kdhHz67a0qLH+6O14OuJ6uwTg6LKO1wHXWsxo5X507FmU6VaBawJWrjORZ2+92QikzlKHku2JgN",
	"3Z8CN9E6zvYaHZhji8KcV5MwcKcqa2VohlPjp9N1LTbV6asvmEqlYWNZ4Glay1UCUm0U6VwsUTqHG04f",
	"x2zMPqAXSYd7vSV9bVee9ZHe5qS9urw31Q7C8JcNP7s63jIAbUur27RqJjjPq0hQwkYeW5vJxofexli+",
	"Ctir51xpm5mdqBVZxnW5tX+4D54evbsrLFcPkuQDWqjCaLZbq9+vhC/NtaO+WbYn+aP79nN5bpa9VfDk",
	"2Z3N+ieJoSKLtmOsRr++rQnSTCUzIblbuVoWq+3IHWxETW8N7yyoNmEHqTrXqffKJ4eaF6KL3UZFYKbi",
	"8uXmpPPo9vrYzFMjmbhP93GcYiw40LWa6DUxthbOGBNepBSqByPb1qEpZ//dNP0z/7twwo3tnD537n3O",
	"zPt866t/pw+jcPT0lWZlpQv9wdMXWhbKX6dFpCuuFlabg5cTBD9yfb2k4vWDgheKQqdszHrLkK0uV/8E",
	"AAD//4xDqRxjEwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
