// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFhtb9s4Ev4rA94BbQFZfmm2t+f91O02veCSRRC7ewfUwWIsjWxuJVIhKSdq4f9+GFKS7VhJGtxuPyWW",
	"SM778zzUV5HootSKlLNi+lWUaLAgR8b/Ossu0CXr93NcXfILfpaSTYwsndRKTMX7u5ISRynwGsi0Abcm",
	"yGRO8PKm0o7SV4AWSjJwdfruH5PXkxiuyFVG8cKF8iu1ymuQGUhnwzkFWyXrz9KKwJaUyExSCpL3SQtr",
	"wpTMTwul3ZrMrbQUgQnnIpyMJ3BpKNEqlewnnKLMKQUyRpuFEpGgOyzKnMRULER6gj/GcUyT7M1CiEhI",
	"jiucLyKhsOBlZ9nAp0JEwtBNJQ2lYupMRZGwyZoK5NS4uuS11hmpVmK7jcS/qX4gcR+VvKkIPlMNMiXl",
	"ZFZLtdplz2mOx0jaUAwXWEOilUOpOMe3aNKFsjlanyReWRqypByU6NZgaVVwQe+FWhr9ByVuMJ68HtLK",
	"kLXDFB3Gid20Yd9UZOpd1J+pfjTgQqpzUiu3FtNx1BP+paFM3j2QgXNpnY/Vwu1a25CLJa2ksnAr3ToU",
	"eoN5RU+E8YD3pbcuHqvQlqOzpVaWfMP/jOkV3VRkHf/ilJPy/2JZ5jJBdn34h2X/v+4d+3dDmZiKvw13",
	"wzQMb+3wPTfdVWMkmDzMw8+YgglGfwKpNpjLFNCsKl9DsY3EmXJkFOYzMhsy/sDv595HRe2My8YPsN6R",
	"ME/s4K/anepKpd/Pq6ZKlIZpSTVZUNoB3UnrRGi9bv7D+H8/5w6wJwvGeVVzAJ9/eAYDr9ElGSdDHxZk",
	"La7oeGh+aX9tKKQf2qX7I3LWdFGH5vDiM9X2hegb0t14f+rsXncL9ZKHjTN6KnO6IIeMGccek8NVDz18",
	"Kys8gcn3vI48Mj2EqWyHIWDowVBnnfFnoOGRwRyt+73QqaehY9NzWZB1WJRwuyYVQr1FC7wN2m0xzNa6",
	"ylPIdJ7r28CA1qFK0fBDU6Br/T1H6wYXzUb413x+2XDePVD/D6URjH+EU1rCZDR5A+M309HJdDSCDxdz",
	"EYlwqpiKFB0NnCyoLzorv/Q020x+of38Mfsua0d234PXk5PRaM+OVO7NiYiYG2RRFWI66uwxfqzIHHVd",
	"oBnvw/1ER6Gx+vqR+YN70j48Ruz074muwsQfBvdrVSzJcHiBg7yyIMildTGcy0IyuDgN49FoxH9xo2UK",
	"v+hZzMHhXQiO3z4ea+S9sA/wX2fekK1yxxIgM7rwrjSkwOzmqLBPwdLBfG47R9AYrPl3Q4dHfvzGDNuW",
	"+UVY9SJAB5RGb2RKaUvInVOsvArpOEe+4cM2kAGF222+Vx9HnJCcaL9Ux8XmDqWkMtLVM462AUmX2z1S",
	"LypXYT4/nwVIlirTx8G+BV8rzOHt5ZlHJoQVKTIyCS1unTa4Ik9xMqGoiYUL4wuGKoUP5BaK+8yzhwXN",
	"ZIgK0CylM2jq7pQlJp9JpTHM1+QtpmTlSnGeCu3kBh0naVn71M5e85IIlpWDBFmDc9+1SZeGvCBoK/Xe",
	"Y1brZ7xQC/W2cmuWkoHVpnDhMwLz8xm8LObns1fsh7TtcRaWuqlqkktWjxxc4PaFchpaURnI5L/xD6N/",
	"QsLTlbEJssCxUArLGhCcqTwfv3sbw2+8wTsBOluogz1omK4VATpv2hlUttTGQY41GZ8qQ5k2FPn3ezy9",
	"UH4J3Mo8B0WcdUMJMReigkrhLn7qNFUElMtCKnStvlbESefan4zG8NFv00Z+8XsClMShc6XzGFsl+QBN",
	"MnCGBoEqBk3PDJpCi0hsyNjQY6N4HI944nRJCksppuK1fxQJZiTfs0PPR9OvYkU92PSBHDRSxR4CcLgq",
	"yJB0frySG1IQELRrybM0HHIaSG//UvepH0R2S4bdnWUbPbn26IK4vb6nqCej0SPCSyeO3MA6Q+GGsBNg",
	"HZ8spUKv6nu0+2HW3u1lzBzoQxE1FzrvUrNu0F5dnqS9lzKmuOsNWOq0frXPhQ9fkJ7Liq1rc//qvmMX",
	"lEoE3tbyRtslB5eclDKscrb6YKr7UJmL+NcpuOfcmg+0z/+rtZbUUPue1Oq0UCu6QoDddwU//d/uMft8",
	"Evq8b166eRjuXS/9lpOnt3RXK94wnjy9oefis43ED9/iXt8903NvVRQ8gwGY/EDx42EnbHpB7Kr5fAHo",
	"RdVO6nS3fRuu+ztx0cmNICeihdIG9r7wYJ63ai0DpfdUh4dBX7ZeELTPRsH9TxfPBLXn3SaPZWwPtB1q",
	"Rf95rGWzQADdt44enPsWMOnArQ9QSDFifToO8jr6s2bhT+rP3TelkMVWNfqKB7346ZrLGVRO6ITK5GIq",
	"hpuR2F5v/xcAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
