// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package server

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xYbW/bug7+K4TuBboBTuK8rHfLPnW97VCsHYo2Gy7uUgyKTSdabcmV5LRekf9+QMl2",
	"ksZ92cHOvi21JD4kHz4kd88ileVKorSGje9ZzjXP0KJ2v06SM26jxdGEz8/pA/0tRhNpkVuhJBuzo7sc",
	"I4sx0BlIlAa7QEhEivDqplAW49fADeSo4eL48D+D4aALF2gLLengVLqTSqYliASENf6djKyicW8piWBy",
	"jEQiMAZB94SBBfIY9fupVHaB+lYYDED7dzmM+gM41xgpGQvCCcdcpBgDaq30VLKA4R3P8hTZmE1ZPOJv",
	"u90uDpL9KWMBE+SXf58FTPKMjp0kHRcKFjCNN4XQGLOx1QUGzEQLzDiFxpY5nTVWCzlnq1XAPmH5SOC+",
	"SHFTIFxjCSJGaUVSCjlfR88q8kcLXGKNKed2sUZ0jeWTYDIhT1HO7YKN+0ELtHONibh7BN2pMNbhMHC7",
	"UMbjnOFcSAO3wi58EpY8LXArmrlWPzCynf5g2MO5RmNq8DcF6nKNPnfW2VPRW5F3JlfSoCPjBx5f4E2B",
	"xtKvSEmL0v2T53kqIk7Qez8M4b/fePbfGhM2Zv/qrYne819N74gIcVEZ8Sa34/CBx6C90fcg5JKnIgau",
	"50XmCmYVsBNpUUueXqJeonYP/jl4XyTW9ScqHGAcEM91AvhZ2WNVyPjPoaqyhLFncqzQgFQW8E4Yyzz1",
	"mtr0pfnnwG3pQuKN06nqAXp/+w0SRa1y1FZ4HmZoDJ/jbtH8t/61RB9+qI9ulshJxaJGaWHvGkuzx9qK",
	"dF3e3xq7V81BNaNio4geixTP0PKYW76LGC2ft0j3SxX7Gb18gDpwyvSY3pEdkoAeiRmopDH+jIz0yLNu",
	"ZJZtBlNu7PdMxa5F7JqeiAyN5VkOtwuUa3dvuQG6CvVV6i4Xx4fD4fDdFpxBONjvhINO/+2kvz8OR+Mw",
	"/D8LWKJ0xi0bs5hb7FiRYRs4I362cOVS/MRN98n0rLRoNg0PB6Mw3LAjpN0fsYCkXWRFxsZhY4/Kf456",
	"hzS+SzgMD+MUeF600YnknyhlHq8CAv09UoUv2G3nPhfZDDW551uI8EFPqfyfRh+4d80jDal5UKMpUkv9",
	"MtEqc49XKk3txmJmntOJrYJZNUC41ryk31V/2sHxlVpenbg9f2rP1zLkWi1FjHHdIRtQNKZkwpIiOgb6",
	"ayC8LNbX3GDytAT44OxmjGiGUaGFLS/JwUqobGo2GmtW2IKnk9NLL4tCJmrXvwNw6eEpHJyfOHXgMEeJ",
	"WkSep8Yqzefo2oyIMKjgUy5cjriM4SPaqSSyOAU3oKghcQlcz4TVXJfNKzMeXaOMuzBZoLMYoxFzSaHJ",
	"lBVLbikus9JF83JIRwKYFRYiTjMqTUl1nIVG15Tr5Bw53ahxdqdyKg8Ku6BRy3eWMZy5iMDk9BJeZZPT",
	"y9eEQ5j6OQMzVSUySgVK75zvr1NpFeXR0J+9oP+v+yZ8BxGVSEIm0AD5gjHMSuBgdeF64uFBF77SBQcC",
	"VDKVW3e4ppYpEbh1pq3m0uRKW0h5idqFSmOiNAbu+0avnEp3BG5FmoJEirrGCKkfcQmF5Gv/sZlrAsBU",
	"ZEJyW8+fEinolPtR2Icv7prS4qe74/Wg68kqrNPHIko7XEcdq7Hj5bpTcaZTJZoFbInaeI6F3X43pCJT",
	"OUqeCzZmQ/enwI24jrO9Rgfm2KIwF9VoDNypyloZmmnV+HF1XYtNdfrqC6ZSadjYHnia1nKVgFQbRToX",
	"S5TO4YbTJzEbs4/oRdLhXq9N39qVZ32ktzl6r64ejLmDMPxt09CujrdMRNvS6lavmgnO8yoSlLCRx9Zm",
	"svGhtzGnrwL25iVX2oZoJ2pFlnFdbi0k7oOnR+/+GsvVoyT5iBaqMJrtXusXLuFLc+2ob5btSf7kvv1a",
	"npvtbxU8e3Zn1f5FYqjIou0Yq9Hvc2uCNOPDTEjudrCWTWs7cocbUdNb0zwLqtXYQarOdepF89kp55Xo",
	"YrdREZipuHy9Ofo8uc4+NfPUSCbu00McZxgLDnStJnpNjK0NNMaEFymF6tHItnVoytk/N17/yn83nHJj",
	"O2cvHYRfMgS/3Prq7+nDKBw9f6XZYelCf/D8hZYN8/dpEemKq4XV5uDlBMGPXN+uqHj9oOCFotApG7Pe",
	"MmSrq9VfAQAA//8cEpRvdBMAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
