// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package server

import (
	"time"
)

const (
	MtlsScopes = "mtls.Scopes"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Message Descriptive error message
	Message string `json:"message"`
}

// FileMetadata defines model for FileMetadata.
type FileMetadata struct {
	// Etag ETag for the file (quoted) as per RFC7232
	Etag string `json:"etag"`

	// Key Unique filename/path of the file
	Key string `json:"key"`

	// LastModified Timestamp when the file was last modified in RFC3339
	LastModified time.Time `json:"last_modified"`

	// Size Size of the file in bytes
	Size int64 `json:"size"`
}

// ListFilesResponse defines model for ListFilesResponse.
type ListFilesResponse struct {
	// FileCount Number of files in the list
	FileCount *int `json:"file_count,omitempty"`

	// Files List of files resulting from the request
	Files []FileMetadata `json:"files"`

	// Prefix Value of the 'prefix' param provided with the request;
	// omitted when prefix is not provided
	Prefix *string `json:"prefix,omitempty"`
}

// IfMatchETagParam defines model for IfMatchETagParam.
type IfMatchETagParam = string

// KeyParam defines model for KeyParam.
type KeyParam = string

// PrefixParam defines model for PrefixParam.
type PrefixParam = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// PreconditionFailed defines model for PreconditionFailed.
type PreconditionFailed = ErrorResponse

// GetFilesParams defines parameters for GetFiles.
type GetFilesParams struct {
	// Prefix List files whose key begins with this value
	Prefix *PrefixParam `form:"prefix,omitempty" json:"prefix,omitempty"`
}

// GetFilesKeyParams defines parameters for GetFilesKey.
type GetFilesKeyParams struct {
	// IfMatch Expected ETag for the file (quoted) as per RFC7232. Return the
	// file only if its ETag matches the one specified in this header;
	// otherwise, return a 412 Precondition Failed error
	IfMatch IfMatchETagParam `json:"If-Match"`
}
