// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	BasicAuthScopes = "basicAuth.Scopes"
)

// ApproveFileRequest defines model for ApproveFileRequest.
type ApproveFileRequest struct {
	// UserId User id of approver
	UserId string `json:"user_id"`
}

// DownloadFileRequest defines model for DownloadFileRequest.
type DownloadFileRequest struct {
	// FilesLocation Location (i.e. path) of file to egress
	FilesLocation string `json:"files_location"`

	// MaxFileSize Maximum allowed file size in bytes
	MaxFileSize int `json:"max_file_size"`

	// RequiredApprovals Min number of approvals required to egress
	RequiredApprovals int `json:"required_approvals"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Message Descriptive error message
	Message string `json:"message"`
}

// FileListResponse defines model for FileListResponse.
type FileListResponse = []FileMetadata

// FileMetadata defines model for FileMetadata.
type FileMetadata struct {
	// Approvals User ids of granted approvals
	Approvals []string `json:"approvals"`

	// FileName Name of file
	FileName string `json:"file_name"`

	// Id Unique file identifier
	Id string `json:"id"`

	// Size Size of file in bytes
	Size int `json:"size"`
}

// ListFilesRequest defines model for ListFilesRequest.
type ListFilesRequest struct {
	// FilesLocation Location (i.e. path) of files to list
	FilesLocation string `json:"files_location"`
}

// FileIdParam defines model for FileIdParam.
type FileIdParam = string

// ProjectIdParam defines model for ProjectIdParam.
type ProjectIdParam = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// GetProjectIdFilesJSONRequestBody defines body for GetProjectIdFiles for application/json ContentType.
type GetProjectIdFilesJSONRequestBody = ListFilesRequest

// GetProjectIdFilesFileIdJSONRequestBody defines body for GetProjectIdFilesFileId for application/json ContentType.
type GetProjectIdFilesFileIdJSONRequestBody = DownloadFileRequest

// PutProjectIdFilesFileIdApproveJSONRequestBody defines body for PutProjectIdFilesFileIdApprove for application/json ContentType.
type PutProjectIdFilesFileIdApproveJSONRequestBody = ApproveFileRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List requested files
	// (GET /{project-id}/files)
	GetProjectIdFiles(c *gin.Context, projectId ProjectIdParam)
	// Download approved file
	// (GET /{project-id}/files/{file-id})
	GetProjectIdFilesFileId(c *gin.Context, projectId ProjectIdParam, fileId FileIdParam)
	// Approve file
	// (PUT /{project-id}/files/{file-id}/approve)
	PutProjectIdFilesFileIdApprove(c *gin.Context, projectId ProjectIdParam, fileId FileIdParam)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetProjectIdFiles operation middleware
func (siw *ServerInterfaceWrapper) GetProjectIdFiles(c *gin.Context) {

	var err error

	// ------------- Path parameter "project-id" -------------
	var projectId ProjectIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "project-id", c.Param("project-id"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter project-id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProjectIdFiles(c, projectId)
}

// GetProjectIdFilesFileId operation middleware
func (siw *ServerInterfaceWrapper) GetProjectIdFilesFileId(c *gin.Context) {

	var err error

	// ------------- Path parameter "project-id" -------------
	var projectId ProjectIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "project-id", c.Param("project-id"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter project-id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "file-id" -------------
	var fileId FileIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "file-id", c.Param("file-id"), &fileId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter file-id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProjectIdFilesFileId(c, projectId, fileId)
}

// PutProjectIdFilesFileIdApprove operation middleware
func (siw *ServerInterfaceWrapper) PutProjectIdFilesFileIdApprove(c *gin.Context) {

	var err error

	// ------------- Path parameter "project-id" -------------
	var projectId ProjectIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "project-id", c.Param("project-id"), &projectId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter project-id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "file-id" -------------
	var fileId FileIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "file-id", c.Param("file-id"), &fileId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter file-id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutProjectIdFilesFileIdApprove(c, projectId, fileId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/:project-id/files", wrapper.GetProjectIdFiles)
	router.GET(options.BaseURL+"/:project-id/files/:file-id", wrapper.GetProjectIdFilesFileId)
	router.PUT(options.BaseURL+"/:project-id/files/:file-id/approve", wrapper.PutProjectIdFilesFileIdApprove)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RYS28bNxD+KwTbQwvsapXauSgnv9IacALDD/hgGAa9HMkMdsk1yVWsCPvfiyG5D2nZ",
	"yEUcH9qbVxzOfJz5vuHQa5qrslISpDV0tqYV06wEC9p9fRQFnPJz/A0/OZhci8oKJemMXkvxVAOZiwKI",
	"4CCtmAvQNKECVytmH2lCJSuBzigapYLThGp4qoUGTmdW15BQkz9CydC7XVVoaqwWckGbJqHnWn2B3O5C",
	"UHmznSCC3b/F0aCxqZQ04JJyyPgFPNVgLH7lSlqQ7k9WVYXIGYLLvhhEuB64/VXDnM7oL1mf8MyvmuxE",
	"a6UvQhAfcvOkh4wT7YN+IEIuWSE4GdSqSeiptKAlKy5BL0E7j2+H71rCcwW5BU5EwEGMA0LAIWkS+lnZ",
	"j6qW/O1QIX2JVJbMXdwmodeS1fZRafEN+Ftmp4/6geDfSFQfi3RETOgjMB6Ud3Nzkx70hrCJZkRRjBng",
	"4PpBVWm1BDz/gKqVVhVoKzyNawP6XvCIqgxoIjhRc8K8H9TTWJ29gm47Z3edoXpArWHOj9VXWSjGv4sG",
	"G4S5L5RPyhjUWVghv4kJTAgK+3dE6LqPVQQWGowZ40xoyZ7v0ereiG8wdvyJPYuyLgkrCvUVuHeIpkRI",
	"8rCygE5LIdGIzqZdAKT5Ahyx20Tc+3SxwkTCCElkXT6A7vPKCtNVf+MMXbh343BbiY/ETraTuZ2DWJE2",
	"OTwqTwnGsEUkfcft1xK80klrmlB4ZmVVYJzT0LHCNdB3rp3Ear3FMCOhzoSxQ9jCQml2CRY3fgLLOLMM",
	"HQXPTGu2ah1366NcfKfKQToGa7zQTGI/HBamQzdi6TYEVy1/b20H+cxKaKkfI3xU0/90V492x1VyiYJo",
	"5fZCYWxVsj+RgxgiJYN0xmqM9cVymJ/SOQzKrhDG7uThVpQxVEwd5LUWdnWJNPPgHpgROfbxMa6/rq7O",
	"ySGub90INLRy9O729+Aera38BSPkXEXKfHRGDi6OyNXFCTlx3YQcnJ/ShBYih6CQMAwdXh6ne+lRwWqD",
	"Vah1EfybWZapCqRRtc5hovQiC7uzB8PTvTT3e5C0wjp513mRMp2nVkPaNbElaONRTSfvJ9OUwxL3oGtW",
	"CTqje5PpZEoTN6S5ZGXrfkJrMpdx/HkBrupYc5efU05n9E+w3XTo+OEc9bPrbbwD9CbZ1nDZ3PmCg7GH",
	"iq9ebTgYEbjZpBZOn9sT5h/T6avFHzXJyHxyAbbW0rQTJnCniU4kWLZ9DykWqYOeDSZjt+Xd7i0bA1mT",
	"0PcviRMbdZ0A67JkeoWiR/z9ccIxmiTGsWwdrqXm5WzzD6Mf5lyyc8fwBfazKBob0H6YpSq3YFNjNfiX",
	"Ww9lrnTJLDY3IbFaSezFFRnkQyCiHVuBE1PnORgzr4ti9ZYc3Z/u797UvXZej9Rtndqx3PN6N62zYO/u",
	"zjpC7/M6Su/wiviPsDzyJnoRyffH16yj45B9XUX+DzQMiWzJNxh8HDkGI8/tHRbT/x/AM8ePGdlySpu7",
	"5u8AAAD//7OlP5B8EgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
