// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	BasicAuthScopes  basicAuthContextKey  = "basicAuth.Scopes"
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
	MTLSScopes       mTLSContextKey       = "mTLS.Scopes"
)

// Defines values for EventAction.
const (
	EventActionApproval  EventAction = "Approval"
	EventActionDownload  EventAction = "Download"
	EventActionRejection EventAction = "Rejection"
)

// Valid indicates whether the value is a known member of the EventAction enum.
func (e EventAction) Valid() bool {
	switch e {
	case EventActionApproval:
		return true
	case EventActionDownload:
		return true
	case EventActionRejection:
		return true
	default:
		return false
	}
}

// Approval defines model for Approval.
type Approval struct {
	// Comment Comment associated with approval (optional)
	Comment *string `json:"comment,omitempty"`

	// Destination Approved egress destination
	Destination string `json:"destination"`

	// UserId User id of approver
	UserId string `json:"user_id"`
}

// ApproveFileRequest defines model for ApproveFileRequest.
type ApproveFileRequest struct {
	// Comment Comment accompanying approval (optional)
	Comment *string `json:"comment,omitempty"`

	// Destination Destination to which the file can be egressed
	Destination string `json:"destination"`

	// UserId User id of approver
	UserId string `json:"user_id"`
}

// DownloadFileRequest defines model for DownloadFileRequest.
type DownloadFileRequest struct {
	// Comment Comment accompanying download request (optional)
	Comment *string `json:"comment,omitempty"`

	// Destination Destination to which the file is egressed
	Destination string `json:"destination"`

	// FilesLocation Location (i.e. path) of file to egress
	FilesLocation string `json:"files_location"`

	// MaxFileSize Maximum allowed file size in bytes
	MaxFileSize int `json:"max_file_size"`

	// RequiredApprovals Min number of approvals required to egress
	RequiredApprovals int `json:"required_approvals"`

	// UserId User id of downloader (optional)
	UserId *string `json:"user_id,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Message Descriptive error message
	Message string `json:"message"`
}

// Event defines model for Event.
type Event struct {
	// Action Action associated with event
	Action *EventAction `json:"action,omitempty"`

	// Comment Comment associated with approval, rejection or download
	Comment *string `json:"comment,omitempty"`

	// Datetime Date and time of event; ISO 8601, millisecond resolution
	Datetime time.Time `json:"datetime"`

	// Destination Egress/download destination
	Destination *string `json:"destination,omitempty"`

	// FileId Unique file identifier
	FileId string `json:"file_id"`

	// UserId User identifier
	UserId string `json:"user_id"`
}

// EventAction Action associated with event
type EventAction string

// EventListResponse defines model for EventListResponse.
type EventListResponse = []Event

// FileListResponse defines model for FileListResponse.
type FileListResponse = []FileMetadata

// FileMetadata defines model for FileMetadata.
type FileMetadata struct {
	// Approvals List of egress approvals
	Approvals []Approval `json:"approvals"`

	// FileName Name of file
	FileName string `json:"file_name"`

	// Id Unique file identifier
	Id string `json:"id"`

	// Size Size of file in bytes
	Size int `json:"size"`
}

// ListFilesRequest defines model for ListFilesRequest.
type ListFilesRequest struct {
	// FilesLocation Location (i.e. path) of files to list
	FilesLocation string `json:"files_location"`
}

// RejectFileRequest defines model for RejectFileRequest.
type RejectFileRequest struct {
	// Comment Comment accompanying rejection (optional)
	Comment *string `json:"comment,omitempty"`

	// Destination Destination to which egressing is denied
	Destination string `json:"destination"`

	// UserId User id of rejecter
	UserId string `json:"user_id"`
}

// FileIdParam defines model for FileIdParam.
type FileIdParam = string

// ProjectIdParam defines model for ProjectIdParam.
type ProjectIdParam = string

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// UnknownError defines model for UnknownError.
type UnknownError = ErrorResponse

// basicAuthContextKey is the context key for basicAuth security scheme
type basicAuthContextKey string

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// mTLSContextKey is the context key for mTLS security scheme
type mTLSContextKey string

// GetProjectIdFilesJSONRequestBody defines body for GetProjectIdFiles for application/json ContentType.
type GetProjectIdFilesJSONRequestBody = ListFilesRequest

// GetProjectIdFilesFileIdJSONRequestBody defines body for GetProjectIdFilesFileId for application/json ContentType.
type GetProjectIdFilesFileIdJSONRequestBody = DownloadFileRequest

// PutProjectIdFilesFileIdApproveJSONRequestBody defines body for PutProjectIdFilesFileIdApprove for application/json ContentType.
type PutProjectIdFilesFileIdApproveJSONRequestBody = ApproveFileRequest

// PutProjectIdFilesFileIdRejectJSONRequestBody defines body for PutProjectIdFilesFileIdReject for application/json ContentType.
type PutProjectIdFilesFileIdRejectJSONRequestBody = RejectFileRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List events
	// (GET /{project-id}/events)
	GetProjectIdEvents(c *gin.Context, projectId ProjectIdParam)
	// List requested files
	// (GET /{project-id}/files)
	GetProjectIdFiles(c *gin.Context, projectId ProjectIdParam)
	// Download approved file
	// (GET /{project-id}/files/{file-id})
	GetProjectIdFilesFileId(c *gin.Context, projectId ProjectIdParam, fileId FileIdParam)
	// Approve file
	// (PUT /{project-id}/files/{file-id}/approve)
	PutProjectIdFilesFileIdApprove(c *gin.Context, projectId ProjectIdParam, fileId FileIdParam)
	// Reject file
	// (PUT /{project-id}/files/{file-id}/reject)
	PutProjectIdFilesFileIdReject(c *gin.Context, projectId ProjectIdParam, fileId FileIdParam)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetProjectIdEvents operation middleware
func (siw *ServerInterfaceWrapper) GetProjectIdEvents(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "project-id" -------------
	var projectId ProjectIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "project-id", c.Param("project-id"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter project-id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(MTLSScopes), []string{})

	c.Set(string(MTLSScopes), []string{})

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(BasicAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProjectIdEvents(c, projectId)
}

// GetProjectIdFiles operation middleware
func (siw *ServerInterfaceWrapper) GetProjectIdFiles(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "project-id" -------------
	var projectId ProjectIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "project-id", c.Param("project-id"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter project-id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(MTLSScopes), []string{})

	c.Set(string(MTLSScopes), []string{})

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(BasicAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProjectIdFiles(c, projectId)
}

// GetProjectIdFilesFileId operation middleware
func (siw *ServerInterfaceWrapper) GetProjectIdFilesFileId(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "project-id" -------------
	var projectId ProjectIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "project-id", c.Param("project-id"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter project-id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "file-id" -------------
	var fileId FileIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "file-id", c.Param("file-id"), &fileId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter file-id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(MTLSScopes), []string{})

	c.Set(string(MTLSScopes), []string{})

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(BasicAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProjectIdFilesFileId(c, projectId, fileId)
}

// PutProjectIdFilesFileIdApprove operation middleware
func (siw *ServerInterfaceWrapper) PutProjectIdFilesFileIdApprove(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "project-id" -------------
	var projectId ProjectIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "project-id", c.Param("project-id"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter project-id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "file-id" -------------
	var fileId FileIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "file-id", c.Param("file-id"), &fileId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter file-id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(MTLSScopes), []string{})

	c.Set(string(MTLSScopes), []string{})

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(BasicAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutProjectIdFilesFileIdApprove(c, projectId, fileId)
}

// PutProjectIdFilesFileIdReject operation middleware
func (siw *ServerInterfaceWrapper) PutProjectIdFilesFileIdReject(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "project-id" -------------
	var projectId ProjectIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "project-id", c.Param("project-id"), &projectId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter project-id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "file-id" -------------
	var fileId FileIdParam

	err = runtime.BindStyledParameterWithOptions("simple", "file-id", c.Param("file-id"), &fileId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter file-id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(MTLSScopes), []string{})

	c.Set(string(MTLSScopes), []string{})

	c.Set(string(BearerAuthScopes), []string{})

	c.Set(string(BasicAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutProjectIdFilesFileIdReject(c, projectId, fileId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/:project-id/events", wrapper.GetProjectIdEvents)
	router.GET(options.BaseURL+"/:project-id/files", wrapper.GetProjectIdFiles)
	router.GET(options.BaseURL+"/:project-id/files/:file-id", wrapper.GetProjectIdFilesFileId)
	router.PUT(options.BaseURL+"/:project-id/files/:file-id/approve", wrapper.PutProjectIdFilesFileIdApprove)
	router.PUT(options.BaseURL+"/:project-id/files/:file-id/reject", wrapper.PutProjectIdFilesFileIdReject)
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fnbbts4E34Vgv9/0QKy5RxaFO5VTt1NN22D2EWADYKAlsY2W4lUScqJG+jdF0NSkg9y7DRudlH0zrKG",
	"M8OZb466p5FMMylAGE279zRjiqVgQNmndzyB0/gc/8PHGHSkeGa4FLRLPwv+LQcy5AkQHoMwfMhB0YBy",
	"fJsxM6YBFSwF2qVI1OIxDaiCbzlXENOuUTkEVEdjSBlyN9MMSbVRXIxoUQT0XMkvEJl1GmSObK0Snu6x",
	"ehRIrDMpNFijHLL4Ar7loA0+RVIYEPYny7KERwyVC79o1PB+hu3/FQxpl/4vrA0eurc6PFFKqgsvxImc",
	"v+khi4lyQt8SLiYs4TGZ8VUR0FNhQAmW9EBNQFmOz6ffZwF3GUQGYsK9HkRbRQhYTYqAfpTmncxF/Hxa",
	"IXyJkIYMrdwioJ8Fy81YKv4d4ue0Ti31LcHfCFQni1RADOgYWOwj7/LysnVQE8K8NksQtVf7KuSteHbH",
	"W6m11727izKi7G0OskzJCUtshlEyA2W4C6ZIpqnXcp7xkXtBmNYy4gyRdcvNmDDPiryQlpQlL2mwaBCr",
	"peGCOWaLvJ06EBMYKdCazBI38Mo1qBseN+QfDYrwmMihV8tmnuU8Vueaq4rZvIrX1TE5wByFYr2WCOKZ",
	"fPNY80XoVSamXIy2Yrvj+iUxktyOeTQmZuzrQMQEGYC3q8X0f8Wax/JWJJLFWzRn7FmWmfnnmZXrB02K",
	"NPomkdEK5mf+DXnB29AmWBVfopktbyM97ybOKbu7Qaobzb/DMuMP7I6neUpYkshbiB1DJCVckMHUADJN",
	"uUAi2u1UAjBbjMBWhdKbNyU4dYMYLojI0wGoGhws0VXqnLtDJW6nSdwm6Cv9CupBjy5AcT6JNFxryU+L",
	"5m2C7XwCXgJsClqzETTiyT1NwKVkUpIGFO5YmiUo59R3Er49qzuKtbctuTXqPPExNK8ri1ZkY/v/UqIH",
	"yyWgINCZV3UNCegFoChnwjKuURORJwkb4M1cT7cE5x+uNgFRpUwiVYUQuoHMmBkwPG3yETNAmIgJvkbg",
	"2Su/Jae9T+TN685OQFKeJFxDJAUmGS2T3N+6duFuZ/d1q7Pf2t3v77zu7r/pdt60X+3s/o1wkyplhnat",
	"Ci2rw2PT0omNqrDKdPMgX3t3i+3GaFs1Ozy6XKw+uxifpR9qtWruK2F8xrWZDT9uINVruyYL3aLiyZRi",
	"U3zG4vNDHPHgBzAsZoatYly9X4681akVtbHQc53QbLbaSLEqKhuUsmZ2s9ei2I/MIR5Jmrz+NMw0F6se",
	"1qWy6m1YnxYwVN/IquglBTMGbgIS2hgdpFf2HU8p4BqrX8K1WRsBC1KaVHWZdYs9Up02t90cOcSiDI4d",
	"vOA/3m46JbfYbiIGIcoVN9MeBoqz3IBpHuFQt6zMn/3+OTnE9wvjIfVzFHK352sdx8ZkeMMBMAWq5Oue",
	"3pWp//1lny7ObEhKcmu6T6fHR+T9ZZ8Y+RWEJhNQGFUxYSPGhTaEkfeXf/XmtLACltVI+2e9htYtNzlL",
	"SP+sR15ECKKhHWcXh2BmbLNrFBM6k8qQhE1BzSAltXxQhB1CuRjKBpcenZGDiyPSvzghrnKRg/NTGtCE",
	"R+DTrd8FHfaOW3uto4TlGgM4V4m/iu6GocxAaJmrCNpSjUJ/OhzouLXXitwZzHfc2BKcR0mLqahlFLSq",
	"NnQCSjutdtp77Q7SI1uWcdqle+1Ou0MDu5+y0Ajv6+VUEdo+wP4/AhtoGH/WUKcx7dI/wFSbsRNHGswt",
	"7q6ac3ZNEi5s1orrhR3XbqezvR3CUh1t2CNcgMmV0DaRYUhGYyWFTOSIRyxJpkSqGLDT96YpArrf2Vkl",
	"ubpKOLfvKQL6yt3r4UNNmzQb0nmaMjUtq2apShEsuM/m2Y28Z6vCdpxns/WhjKdb89tS2Srm0yH2fMVP",
	"xM1Ss/QAbPz9Ia4A5JxgcbKBy2d2us8PrYC+2u1sInBmwdeAx9oG/u7NwAzv/bRXbA5R9x3gyUAN1p6Y",
	"/eDws3DdtAl6MrRlZMC0tFHgPlTUqlRT2IAL9FbQ9IGhYW/tBRFlIQ4x0XkUgdbDPEmmzwns/c7++kPV",
	"cv9fjoTSueUK0QXD+lgIPb3td/OGmDjPG2PCL2l/kdBoWDlvFBn7y72YxfAsZCuP/MbuCux662+KWDe1",
	"PBawbsL7RfC6PK5uD65+KPwN11VwdcYv0Toz8lo8zU6lV9fleHh1jciZ/T1PZ/+px+Sra0SO+5DsYOoG",
	"tXCyQ4vr4p8AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
