---
name: Test
on:
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  unit:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # version 7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # version 6.5.0, See: https://github.com/actions/setup-go/releases
        with:
          go-version: '1.25'

      - name: Run unit tests
        run: make test-unit

  e2e:
    runs-on: ubuntu-latest
    needs: [unit]
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # version 7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # version 6.5.0, See: https://github.com/actions/setup-go/releases
        with:
          go-version: '1.25'

      - name: Install k3d
        run: |
          wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash

      - name: Run e2e tests
        run: make test-e2e
